services:
  web:
    build: .
    container_name: bims_web
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./database:/var/www/database
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: bims_db
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: nlabims
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
